Use the correct address when creating zeroconf entries
nymea/nymea-zeroconf-plugin-dnssd pull request #2
Opened 2020-06-10 11:26 UTC by mzanetti

2020-07-01 12:50 UTC, QSchulz approved these changes
From a quick look, looks good to me

2020-07-02 11:56 UTC, Boernsman requested changes

2020-07-02 11:56 UTC, Boernsman commented on zeroconfservicebrowserdnssd.cpp
> +    // From here on we resolve the serviec. First, when using the AVAHI libdns compat lib.
*service

2020-07-02 11:56 UTC, Boernsman commented on zeroconfservicebrowserdnssd.cpp
> +    // To behave better on systems where DNSServiceGetAddrInfo is available, let's use thae
*that

2020-07-02 12:07 UTC, Boernsman approved these changes

2020-07-03 11:40 UTC, merged